/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;
//import App.Calculator;

/**
 *
 * @author dylan
 */
public class CalculatorWindow extends javax.swing.JFrame {

    public double number, number2, answer;
    public String operator;
    boolean separate = false;

    /**
     * Creates new form CalculatorWindow
     */
    public CalculatorWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton15 = new javax.swing.JButton();
        OneButton = new javax.swing.JButton();
        TwoButton = new javax.swing.JButton();
        ThreeButton = new javax.swing.JButton();
        FourButton = new javax.swing.JButton();
        FiveButton = new javax.swing.JButton();
        SixButton = new javax.swing.JButton();
        SevenButton = new javax.swing.JButton();
        EightButton = new javax.swing.JButton();
        NineButton = new javax.swing.JButton();
        ZeroButton = new javax.swing.JButton();
        DecimalPointButton = new javax.swing.JButton();
        AddButton = new javax.swing.JButton();
        MinusButton = new javax.swing.JButton();
        MultiplyButton = new javax.swing.JButton();
        DivideButton = new javax.swing.JButton();
        ClearNumberFieldButton = new javax.swing.JButton();
        EqualsButton = new javax.swing.JButton();
        NumberField = new javax.swing.JTextField();
        Separator = new javax.swing.JSeparator();

        jButton15.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OneButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OneButton.setText("1");
        OneButton.setVerifyInputWhenFocusTarget(false);
        OneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OneButtonMouseClicked(evt);
            }
        });

        TwoButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TwoButton.setText("2");
        TwoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TwoButtonMouseClicked(evt);
            }
        });

        ThreeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ThreeButton.setText("3");
        ThreeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThreeButtonMouseClicked(evt);
            }
        });

        FourButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FourButton.setText("4");
        FourButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FourButtonMouseClicked(evt);
            }
        });

        FiveButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FiveButton.setText("5");
        FiveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FiveButtonMouseClicked(evt);
            }
        });

        SixButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SixButton.setText("6");
        SixButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SixButtonMouseClicked(evt);
            }
        });

        SevenButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SevenButton.setText("7");
        SevenButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SevenButtonMouseClicked(evt);
            }
        });

        EightButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EightButton.setText("8");
        EightButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EightButtonMouseClicked(evt);
            }
        });

        NineButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NineButton.setText("9");
        NineButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NineButtonMouseClicked(evt);
            }
        });

        ZeroButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ZeroButton.setText("0");
        ZeroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ZeroButtonMouseClicked(evt);
            }
        });

        DecimalPointButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DecimalPointButton.setText(".");
        DecimalPointButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DecimalPointButtonMouseClicked(evt);
            }
        });

        AddButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddButton.setText("+");
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButtonMouseClicked(evt);
            }
        });

        MinusButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MinusButton.setText("-");
        MinusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinusButtonMouseClicked(evt);
            }
        });

        MultiplyButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MultiplyButton.setText("x");
        MultiplyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MultiplyButtonMouseClicked(evt);
            }
        });

        DivideButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DivideButton.setText("÷");
        DivideButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DivideButtonMouseClicked(evt);
            }
        });

        ClearNumberFieldButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ClearNumberFieldButton.setText("AC");
        ClearNumberFieldButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearNumberFieldButtonMouseClicked(evt);
            }
        });

        EqualsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EqualsButton.setText("=");
        EqualsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EqualsButtonMouseClicked(evt);
            }
        });

        NumberField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(NumberField)
                            .addGap(18, 18, 18)
                            .addComponent(ClearNumberFieldButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ZeroButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(OneButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                .addComponent(FourButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SevenButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(DecimalPointButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(EqualsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(TwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(ThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(MinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(EightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(NineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(DivideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(FiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(SixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(MultiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearNumberFieldButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DivideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MultiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EqualsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DecimalPointButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ZeroButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZeroButtonMouseClicked
        NumberField.setText(NumberField.getText() + "0");
        getInput();
    }//GEN-LAST:event_ZeroButtonMouseClicked

    private void OneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OneButtonMouseClicked
        NumberField.setText(NumberField.getText() + "1");
        getInput();
    }//GEN-LAST:event_OneButtonMouseClicked

    private void TwoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TwoButtonMouseClicked
        NumberField.setText(NumberField.getText() + "2");
        getInput();
    }//GEN-LAST:event_TwoButtonMouseClicked

    private void ThreeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThreeButtonMouseClicked
        NumberField.setText(NumberField.getText() + "3");
        getInput();
    }//GEN-LAST:event_ThreeButtonMouseClicked

    private void FourButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FourButtonMouseClicked
        NumberField.setText(NumberField.getText() + "4");
        getInput();
    }//GEN-LAST:event_FourButtonMouseClicked

    private void FiveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FiveButtonMouseClicked
        NumberField.setText(NumberField.getText() + "5");
        getInput();
    }//GEN-LAST:event_FiveButtonMouseClicked

    private void SixButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SixButtonMouseClicked
        NumberField.setText(NumberField.getText() + "6");
        getInput();
    }//GEN-LAST:event_SixButtonMouseClicked

    private void SevenButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SevenButtonMouseClicked
        NumberField.setText(NumberField.getText() + "7");
        getInput();
    }//GEN-LAST:event_SevenButtonMouseClicked

    private void EightButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EightButtonMouseClicked
        NumberField.setText(NumberField.getText() + "8");
        getInput();
    }//GEN-LAST:event_EightButtonMouseClicked

    private void NineButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NineButtonMouseClicked
        NumberField.setText(NumberField.getText() + "9");
        getInput();
    }//GEN-LAST:event_NineButtonMouseClicked

    private void DecimalPointButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_DecimalPointButtonMouseClicked
        NumberField.setText(NumberField.getText() + ".");
        getInput();
    }// GEN-LAST:event_DecimalPointButtonMouseClicked

  
    private void AddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseClicked
        separate = true;
        NumberField.setText("");
        operator = "+";
    }//GEN-LAST:event_AddButtonMouseClicked

    private void MinusButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_MinusButtonMouseClicked
        separate = true;
        NumberField.setText("");
        operator = "-";
    }// GEN-LAST:event_MinusButtonMouseClicked

    private void MultiplyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MultiplyButtonMouseClicked
        separate = true;
        NumberField.setText("");
        operator = "*";
    }//GEN-LAST:event_MultiplyButtonMouseClicked

    private void DivideButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DivideButtonMouseClicked
        separate = true;
        NumberField.setText("");
        operator = "/";
    }//GEN-LAST:event_DivideButtonMouseClicked

    private void EqualsButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_EqualsButtonMouseClicked
        calculate();
        separate = false;
    }// GEN-LAST:event_EqualsButtonMouseClicked

    private void ClearNumberFieldButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ClearNumberFieldButtonMouseClicked
        NumberField.setText("");
    }// GEN-LAST:event_ClearNumberFieldButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CalculatorWindow calculator;
                calculator = new CalculatorWindow();
                calculator.setVisible(true);
                calculator.setResizable(false);

            }
        });
    }

    public void getInput() {
        if (separate == false) {
            number = Double.parseDouble(NumberField.getText());
        } else {
            number2 = Double.parseDouble(NumberField.getText());
        }
    }

    public void calculate() {
        switch (operator) {
            case "+":
                answer = number + number2;
                answer = Math.round(answer * 100.0) / 100.0;
                NumberField.setText(String.valueOf(answer));
                break;
            case "-":
                answer = number - number2;
                answer = Math.round(answer * 100.0) / 100.0;
                NumberField.setText(String.valueOf(answer));
                break;
            case "*":
                answer = number * number2;
                answer = Math.round(answer * 100.0) / 100.0;
                NumberField.setText(String.valueOf(answer));
                break;
            case "/":
                answer = number / number2;
                answer = Math.round(answer * 100.0) / 100.0;
                NumberField.setText(String.valueOf(answer));
                break;
            default:
                throw new AssertionError();
        }
        number = 0;
        number2 = 0;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton ClearNumberFieldButton;
    private javax.swing.JButton DecimalPointButton;
    private javax.swing.JButton DivideButton;
    private javax.swing.JButton EightButton;
    private javax.swing.JButton EqualsButton;
    private javax.swing.JButton FiveButton;
    private javax.swing.JButton FourButton;
    private javax.swing.JButton MinusButton;
    private javax.swing.JButton MultiplyButton;
    private javax.swing.JButton NineButton;
    private javax.swing.JTextField NumberField;
    private javax.swing.JButton OneButton;
    private javax.swing.JSeparator Separator;
    private javax.swing.JButton SevenButton;
    private javax.swing.JButton SixButton;
    private javax.swing.JButton ThreeButton;
    private javax.swing.JButton TwoButton;
    private javax.swing.JButton ZeroButton;
    private javax.swing.JButton jButton15;
    // End of variables declaration//GEN-END:variables
}
